language: node_js
node_js:
  # - node # 10.X is currently broken due to deprecated Buffer in Yarn
  - "9"
  - "lts/*" # 8.X
cache:
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - psql -c 'CREATE DATABASE udiadbtest;' -U postgres
after_script:
  - greenkeeper-lockfile-upload
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - SQL_HOST=localhost
    - SQL_USER=postgres
    - SQL_PASSWORD=
    - SQL_DB=udiadbtest
    - SQL_PORT=5432
