version: '3'

services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
  test:
    build: .
    depends_on:
      - db
    links:
      - db:db
    command: sh -c "sleep 5 && yarn test"
    environment:
      SQL_DB: testdb
      SQL_HOST: db
      SQL_USER: postgres
      SQL_PASSWORD: mysecretpassword
      SQL_PORT: 5432
